name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y curl
      
    - name: Install Rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      shell: bash
      
    - name: Add Rust to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
    - name: Build project
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
