name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      env:
        PATH: $HOME/.cargo/bin:$PATH
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
